---
language: ruby
bundler_args: --without development --path .vendor
script:
  - RAKE_ENV=ci bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.1
env:
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
matrix:
  exclude:
  - rvm: 2.3.1
    env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 
